[browser]
gatherUsageStats = false

[client]
html = """
<head>
    <meta name="google-site-verification" content="bDW2z3cf_Tl2irHZicspzRBDWTOJC2_JWxgJL3VDFAA" />
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4PN5EQ2JVB"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-4PN5EQ2JVB');
    </script>
</head>
"""
